apiVersion: apps/v1
kind: Deployment
metadata:
  name:  notification
  labels:
    app:  notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  notification
  template:
    metadata:
      labels:
        app:  notification
    spec:
      containers:
      - image:  notification:latest
        name:  notification
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /api/notification/health
            port: 3000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/notification/health
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google
              key: GOOGLE_CLIENT_SECRET
        - name: GOOGLE_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: google
              key: GOOGLE_REFRESH_TOKEN
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: google
              key: EMAIL_USER
        - name: CLOUD_AMQP_URL
          valueFrom:
            secretKeyRef:
              name: database
              key: CLOUD_AMQP_URL
        ports:
        - containerPort:  3000
          name: noti-main